import mongoose from "mongoose";

/**
 * File Schema: Describes code or data files stored within an artifact (e.g. index.html)
 */
const fileSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },
  content: {
    type: String,
    required: true,
  },
});

/**
 * Artifact Schema: Describes complex output objects (like a generated project directory or standalone documents)
 */
const artifactSchema = new mongoose.Schema(
  {
    id: {
      type: String,
      required: true,
    },
    // The type of artifact generated by an agent
    type: {
      type: String,
      enum: ["Project", "File"],
      required: true,
    },
    // List of files contained inside the artifact
    files: {
      type: [fileSchema],
    },
  },
  {
    _id: false, // Prevents automatic generation of _id sub-documents
  },
);

/**
 * Message Schema: Defines individual conversation messages exchanged between user and agents
 */
const messageSchema = new mongoose.Schema(
  {
    // The parent conversation this message belongs to
    conversationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Conversation",
    },
    // The sender of the message
    role: {
      type: String,
      enum: ["user", "assistant"],
    },
    // The main textual content/markdown of the message
    content: {
      type: String,
    },
    // Optional generated image URLs
    images: {
      type: [String],
    },
    // Optional generated artifacts (e.g., code files)
    artifacts: {
      type: [artifactSchema],
    },
    // The identifier of the agent that generated the response
    agent: {
      type: String,
    },
  },
  { timestamps: true }, // Automatically tracks message creation and update times
);

const Message = mongoose.model("Message", messageSchema);

export default Message;
