import { getModel } from "../config/llmmodel.ts";
import { AgentState } from "../graph/state.ts";
import PDFDocument from "pdfkit";
import { uploadFileToS3 } from "../utils/uploadtos3.ts";
import { getFromS3 } from "../utils/getFroms3.ts";

const generatePDFBuffer = (content: string): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, bufferPages: true });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", (err) => reject(err));

      const lines = content.split("\n");
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i].trim();
        if (!line) {
          doc.moveDown(0.5);
          continue;
        }

        if (line.startsWith("# ")) {
          const titleText = line.replace("# ", "").trim();
          doc
            .fontSize(22)
            .fillColor("#1a365d")
            .text(titleText, { align: "center" });
          doc.moveDown(1.5);
        } else if (line.startsWith("## ")) {
          const headerText = line.replace("## ", "").trim();
          doc.fontSize(15).fillColor("#2b6cb0").text(headerText);
          doc.moveDown(0.5);
        } else if (line.startsWith("### ")) {
          const subheaderText = line.replace("### ", "").trim();
          doc.fontSize(12).fillColor("#4a5568").text(subheaderText);
          doc.moveDown(0.5);
        } else {
          // Normal paragraph text
          doc.fontSize(10).fillColor("#2d3748").text(line, {
            align: "justify",
            lineGap: 3,
          });
          doc.moveDown(0.8);
        }
      }

      // Add headers and footers to all pages dynamically
      const pages = doc.bufferedPageRange();
      for (let i = 0; i < pages.count; i++) {
        doc.switchToPage(i);

        // Header (only on pages after the first page, or on all pages)
        doc
          .fontSize(8)
          .fillColor("#718096")
          .text("Multi-Agent AI Platform - Generated Report", 50, 25, {
            align: "left",
          });
        doc
          .moveTo(50, 37)
          .lineTo(562, 37)
          .strokeColor("#cbd5e0")
          .lineWidth(0.5)
          .stroke();

        // Footer
        doc
          .fontSize(8)
          .fillColor("#718096")
          .text(`Page ${i + 1} of ${pages.count}`, 50, 755, {
            align: "center",
          });
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

export const pdfAgent = async (state: typeof AgentState.State) => {
  try {
    // 1. Collect/research information using the LLM
    const llm = await getModel("pdf");
    const response = await llm.invoke([
      {
        role: "system",
        content:
          "You are an AI research assistant and technical writer. Research the topic requested by the user and produce a comprehensive, structured report. Format the output using simple Markdown headers (# for Document Title, ## for main section headers, ### for subsection headers, and plain text for paragraphs). Do not use tables, lists, or inline formatting like bold/italic markdown syntax inside the text blocks. Ensure the report is detailed and complete, starting with an introduction and ending with a conclusion.",
      },
      {
        role: "user",
        content: state.prompt,
      },
    ]);

    const contentStr =
      typeof response.content === "string"
        ? response.content
        : Array.isArray(response.content)
          ? response.content.map((c) => ("text" in c ? c.text : "")).join("")
          : "";

    const reportContent = contentStr.trim();
    if (!reportContent) {
      throw new Error("No content generated by the AI model.");
    }

    // 2. Generate PDF document
    const pdfBuffer = await generatePDFBuffer(reportContent);

    // 3. Upload to S3
    const filename = `generated-pdfs/document-${Date.now()}.pdf`;
    await uploadFileToS3(filename, pdfBuffer, "application/pdf");

    // 4. Generate signed download URL (valid for 24 hours)
    const downloadUrl = await getFromS3(filename, 24 * 60 * 60);

    const artifacts = [
      {
        id: `pdf-${Date.now()}`,
        type: "File",
        files: [
          {
            name: "document.pdf",
            content: `PDF report has been successfully generated and uploaded to secure storage. You can download it directly here: ${downloadUrl}`,
          },
        ],
      },
    ];

    const aiResponse = `I've researched the topic and generated a professional PDF report for you.\n\n[📥 Click here to download the PDF Document](${downloadUrl})`;

    return {
      aiResponse,
      artifacts,
    };
  } catch (error: any) {
    console.error("PDF agent error:", error);
    return {
      aiResponse: `Sorry, I encountered an error while generating your PDF: ${error.message || error}`,
      artifacts: [],
    };
  }
};
