import { getModel } from "../config/llmmodel.ts";
import { AgentState } from "../graph/state.ts";
import pptxgen from "pptxgenjs";
import { uploadFileToS3 } from "../utils/uploadtos3.ts";
import { getFromS3 } from "../utils/getFroms3.ts";

const generatePPTBuffer = async (
  slides: Array<{ title: string; bulletPoints: string[] }>,
): Promise<Buffer> => {
  const pptx = new (pptxgen as any)();

  // Set presentation properties
  pptx.layout = "LAYOUT_16x9";

  for (let i = 0; i < slides.length; i++) {
    const slideData = slides[i];
    const slide = pptx.addSlide();

    // Set background color for a professional template look
    slide.background = { fill: "f7fafc" };

    if (i === 0) {
      // Title slide layout
      // Add a decorative header stripe
      slide.addShape(pptx.shapes.RECTANGLE, {
        x: 0,
        y: 0,
        w: 10,
        h: 0.3,
        fill: { color: "1a365d" },
      });

      slide.addText(slideData.title, {
        x: 1.0,
        y: 2.0,
        w: 8.0,
        h: 1.5,
        fontSize: 36,
        bold: true,
        color: "1a365d",
        align: "center",
      });

      if (slideData.bulletPoints && slideData.bulletPoints.length > 0) {
        // Render points as subtitle / intro points
        slide.addText(slideData.bulletPoints.join("\n\n"), {
          x: 1.5,
          y: 4.0,
          w: 7.0,
          h: 2.0,
          fontSize: 16,
          color: "4a5568",
          align: "center",
        });
      }
    } else {
      // Content slide layout
      // Add decorative banner on the left
      slide.addShape(pptx.shapes.RECTANGLE, {
        x: 0.4,
        y: 0.5,
        w: 0.1,
        h: 0.8,
        fill: { color: "2b6cb0" },
      });

      // Title
      slide.addText(slideData.title, {
        x: 0.7,
        y: 0.4,
        w: 8.5,
        h: 1.0,
        fontSize: 24,
        bold: true,
        color: "1a365d",
      });

      // Bullet points
      if (slideData.bulletPoints && slideData.bulletPoints.length > 0) {
        const textObjects = slideData.bulletPoints.map((bp) => {
          return {
            text: bp,
            options: { bullet: true, fontSize: 14, color: "2d3748" },
          };
        });

        slide.addText(textObjects, {
          x: 0.7,
          y: 1.6,
          w: 8.5,
          h: 4.5,
        });
      }
    }

    // Add slide numbers in the footer (skip on Title slide)
    if (i > 0) {
      slide.addText(`Slide ${i + 1}`, {
        x: 8.5,
        y: 5.2,
        w: 1.0,
        h: 0.3,
        fontSize: 10,
        color: "718096",
        align: "right",
      });
    }
  }

  const arrayBuffer = await pptx.write("arraybuffer");
  return Buffer.from(arrayBuffer as ArrayBuffer);
};

export const pptAgent = async (state: typeof AgentState.State) => {
  try {
    // 1. Collect/research information using the LLM and format it as slide data
    const llm = await getModel("ppt");
    const response = await llm.invoke([
      {
        role: "system",
        content:
          "You are a professional presentation designer. Research the topic requested by the user and structure it into a detailed slide presentation. Return the content ONLY as a valid JSON array of slide objects. Each slide object must contain: 'title' (string, the header of the slide) and 'bulletPoints' (an array of strings, 2-4 points containing the detailed content for that slide). The first slide should be a Title/Intro slide. Do not include any markdown backticks, conversational intro/outro text, or other text outside the JSON array block.",
      },
      {
        role: "user",
        content: state.prompt,
      },
    ]);

    const contentStr =
      typeof response.content === "string"
        ? response.content
        : Array.isArray(response.content)
          ? response.content.map((c) => ("text" in c ? c.text : "")).join("")
          : "";

    const reportContent = contentStr.trim();
    if (!reportContent) {
      throw new Error("No content generated by the AI model.");
    }

    let slides: Array<{ title: string; bulletPoints: string[] }>;
    try {
      let jsonText = reportContent;
      if (jsonText.startsWith("```")) {
        jsonText = jsonText
          .replace(/^```(json)?/, "")
          .replace(/```$/, "")
          .trim();
      }
      slides = JSON.parse(jsonText);
      if (!Array.isArray(slides)) {
        throw new Error("Parsed JSON is not an array");
      }
    } catch (e) {
      console.warn(
        "JSON parsing failed, falling back to simple presentation layout:",
        e,
      );
      // Fallback layout
      slides = [
        {
          title: state.prompt || "Presentation",
          bulletPoints: ["Presentation generated on request."],
        },
        {
          title: "Detailed Content",
          bulletPoints: reportContent
            .split("\n")
            .filter((l) => l.trim())
            .slice(0, 5),
        },
      ];
    }

    // 2. Generate PPTX document
    const pptBuffer = await generatePPTBuffer(slides);

    // 3. Upload to S3
    const filename = `generated-ppts/presentation-${Date.now()}.pptx`;
    await uploadFileToS3(
      filename,
      pptBuffer,
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    );

    // 4. Generate signed download URL (valid for 24 hours)
    const downloadUrl = await getFromS3(filename, 24 * 60 * 60);

    const artifacts = [
      {
        id: `ppt-${Date.now()}`,
        type: "File",
        files: [
          {
            name: "presentation.pptx",
            content: `PPTX presentation slides have been successfully generated and uploaded to secure storage. You can download it directly here: ${downloadUrl}`,
          },
        ],
      },
    ];

    const aiResponse = `I've researched the topic and generated a professional slide presentation for you.\n\n[📥 Click here to download the PowerPoint Presentation](${downloadUrl})`;

    return {
      aiResponse,
      artifacts,
    };
  } catch (error: any) {
    console.error("PPT agent error:", error);
    return {
      aiResponse: `Sorry, I encountered an error while generating your presentation: ${error.message || error}`,
      artifacts: [],
    };
  }
};
